# Generated by Django 3.0.6 on 2020-06-05 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyempsalary',
            name='deductions',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='monthlyempsalary',
            name='over_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='monthlyempsalary',
            name='reimbursements',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='monthlyempsalary',
            name='special_allowances',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='empleaveapplied',
            name='action_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_by', to='api.Employee'),
        ),
        migrations.AlterField(
            model_name='monthlyempsalary',
            name='cca_allowance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='monthlyempsalary',
            name='esi_employee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='monthlyempsalary',
            name='esi_employer',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='monthlyempsalary',
            name='net_employee_payable',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='monthlyempsalary',
            name='pf_employee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='monthlyempsalary',
            name='pf_employer',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='monthlyempsalary',
            name='pt',
            field=models.FloatField(default=0.0),
        ),
    ]
