# Generated by Django 3.0.7 on 2020-06-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingstatus',
            name='ts_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testingnames',
            name='average_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='testingnames',
            name='tn_cron_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
