# Generated by Django 3.0.7 on 2020-07-01 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200617_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='login_image',
            field=models.FileField(blank=True, null=True, upload_to='Employees/Attendance/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'log', 'mp4', 'png', 'jpeg', 'jpg', 'webm'])]),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='logout_image',
            field=models.FileField(blank=True, null=True, upload_to='Employees/Attendance/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'log', 'mp4', 'png', 'jpeg', 'jpg', 'webm'])]),
        ),
        migrations.AlterField(
            model_name='documents',
            name='aadharcard',
            field=models.FileField(blank=True, null=True, upload_to='Employees/Documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'log', 'mp4', 'png', 'jpeg', 'jpg', 'webm'])]),
        ),
        migrations.AlterField(
            model_name='documents',
            name='address_proof',
            field=models.FileField(blank=True, null=True, upload_to='Employees/Documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'log', 'mp4', 'png', 'jpeg', 'jpg', 'webm'])]),
        ),
        migrations.AlterField(
            model_name='documents',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='Employees/Documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'log', 'mp4', 'png', 'jpeg', 'jpg', 'webm'])]),
        ),
        migrations.AlterField(
            model_name='documents',
            name='permanent_proof',
            field=models.FileField(blank=True, null=True, upload_to='Employees/Documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'log', 'mp4', 'png', 'jpeg', 'jpg', 'webm'])]),
        ),
    ]
