# Generated by Django 3.0.7 on 2020-07-13 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200701_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctc', models.FloatField()),
                ('basic', models.FloatField()),
                ('hra', models.FloatField()),
                ('conveyance_allowances', models.FloatField()),
                ('medical_allowance', models.FloatField()),
                ('cca_allowance', models.FloatField()),
                ('pf_employer', models.FloatField()),
                ('pf_employee', models.FloatField()),
                ('pt', models.FloatField()),
                ('esi_employer', models.FloatField()),
                ('esi_employee', models.FloatField()),
                ('emp_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='empsalary', to='api.Employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='testingstatus',
            name='tn_id',
        ),
        migrations.DeleteModel(
            name='TestingNames',
        ),
        migrations.DeleteModel(
            name='TestingStatus',
        ),
    ]
