# Generated by Django 3.0.6 on 2020-06-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymembers',
            old_name='family_Member_name',
            new_name='family_member_name',
        ),
    ]
