# Generated by Django 3.0.6 on 2020-06-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20200602_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyempsalary',
            old_name='No_of_days',
            new_name='no_of_days',
        ),
    ]
