# Generated by Django 3.0.6 on 2020-06-03 12:19

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('connector_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_mainpoint_id', models.IntegerField()),
                ('end_mainpoint_id', models.IntegerField()),
                ('connector_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('process_id', models.AutoField(primary_key=True, serialize=False)),
                ('process_name', models.CharField(max_length=50)),
                ('process_description', models.CharField(max_length=50)),
                ('process_training', models.FileField(upload_to='dropbox/videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'log', 'mp4', 'png', 'jpeg', 'jpg', 'webm'])])),
                ('process_department', models.PositiveSmallIntegerField()),
                ('process_time_allocated', models.TimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessMainid',
            fields=[
                ('process_mainid', models.AutoField(primary_key=True, serialize=False)),
                ('main_name', models.CharField(max_length=50)),
                ('offsetx', models.FloatField()),
                ('offsety', models.FloatField()),
                ('main_attachment', models.FileField(upload_to='dropbox/videos_main', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'mp4', 'png', 'jpeg', 'jpg'])])),
                ('main_description', models.TextField(blank=True, max_length=200)),
                ('main_department', models.SmallIntegerField()),
                ('process_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='process.Process')),
            ],
        ),
        migrations.CreateModel(
            name='RepeatTask',
            fields=[
                ('repeat_id', models.AutoField(primary_key=True, serialize=False)),
                ('repeat_type', models.CharField(max_length=50)),
                ('interval_repeat', models.IntegerField()),
                ('end_date', models.DateField()),
                ('weekly_days', django.contrib.postgres.fields.jsonb.JSONField()),
                ('monthly_date', models.IntegerField()),
                ('yearly_date', models.DateField()),
                ('yearly_month', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegularTask',
            fields=[
                ('regular_task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=50)),
                ('task_deptname', models.CharField(max_length=50)),
                ('task_type', models.CharField(max_length=50)),
                ('members', django.contrib.postgres.fields.jsonb.JSONField()),
                ('task_description', models.TextField(max_length=100)),
                ('task_files', django.contrib.postgres.fields.jsonb.JSONField()),
                ('task_duedate', models.DateField()),
                ('prc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regularprocess', to='process.Process')),
                ('repeat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repeats', to='process.RepeatTask')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessSubpoint',
            fields=[
                ('process_subpointid', models.AutoField(primary_key=True, serialize=False)),
                ('subpoint_name', models.CharField(max_length=50)),
                ('subpoint_attachment', models.FileField(upload_to='dropbox/videos_subprocess', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'mp4', 'png', 'jpeg', 'jpg'])])),
                ('subpoint_description', models.TextField(blank=True, max_length=100)),
                ('pmain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainprocess', to='process.ProcessMainid')),
            ],
        ),
    ]
