# Generated by Django 3.0.7 on 2020-06-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='process_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='regulartask',
            name='task_description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
