# Generated by Django 3.0.7 on 2020-07-01 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_auto_20200625_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='process_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procdepts', to='process.Departments'),
        ),
        migrations.DeleteModel(
            name='Templates',
        ),
    ]
