# Generated by Django 3.0.7 on 2020-06-15 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_auto_20200612_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='connections',
            name='connection_process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='process.Process'),
        ),
    ]
