# Generated by Django 3.0.7 on 2020-07-01 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_auto_20200701_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='process_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depts', to='process.Departments'),
        ),
    ]
