# Generated by Django 3.0.7 on 2020-07-01 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_auto_20200701_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connections',
            name='end_mainpoint_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainconnector', to='process.ProcessMainid'),
        ),
        migrations.AlterField(
            model_name='connections',
            name='start_mainpoint_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainconnect', to='process.ProcessMainid'),
        ),
    ]
