# Generated by Django 3.0.7 on 2020-07-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_auto_20200701_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processmainid',
            name='main_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='processsubpoint',
            name='subpoint_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
