# Generated by Django 3.0.7 on 2020-07-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_auto_20200703_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='dept_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
