# Generated by Django 3.0.7 on 2020-07-22 06:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0009_auto_20200703_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('flow_id', models.AutoField(primary_key=True, serialize=False)),
                ('percentage_complete', models.FloatField()),
                ('regular_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskflow', to='process.RegularTask')),
            ],
        ),
        migrations.CreateModel(
            name='FlowMainChecklist',
            fields=[
                ('flow_main_id', models.AutoField(primary_key=True, serialize=False)),
                ('files_main', models.FileField(blank=True, null=True, upload_to='flow_main_chklist/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'mp4', 'png', 'jpeg', 'jpg'])])),
                ('is_checked', models.BooleanField(blank=True, default=False)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='process.Flow')),
                ('mprocess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainprocessflow', to='process.ProcessMainid')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('flow_time_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('starttime', models.DurationField(blank=True)),
                ('stoptime', models.DurationField(blank=True)),
                ('total_time', models.DurationField(blank=True)),
                ('mainpoints', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintime', to='process.ProcessMainid')),
                ('subpoints', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtime', to='process.ProcessSubpoint')),
                ('tflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeflows', to='process.Flow')),
            ],
        ),
        migrations.CreateModel(
            name='FlowSubpointChecklist',
            fields=[
                ('flow_subpoint_id', models.AutoField(primary_key=True, serialize=False)),
                ('files_main', models.FileField(blank=True, null=True, upload_to='flow_subpt_chklist/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'mp4', 'png', 'jpeg', 'jpg'])])),
                ('flow_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainflow', to='process.FlowMainChecklist')),
                ('flowpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowss', to='process.Flow')),
                ('subpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='process.ProcessSubpoint')),
            ],
        ),
    ]
